apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.40
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: "todo_management"
        - name: MYSQL_USER
          value: "demo"
        - name: MYSQL_PASSWORD
          value: "Vamc2004"
        - name: MYSQL_ROOT_PASSWORD
          value: "Vamc2004"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql
        configMap:
          name: init-sql-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-configmap
data:
  init.sql: |
    CREATE TABLE users (
      id int(3) NOT NULL AUTO_INCREMENT,
      first_name varchar(20) DEFAULT NULL,
      last_name varchar(20) DEFAULT NULL,
      username varchar(250) DEFAULT NULL,
      password varchar(20) DEFAULT NULL,
      PRIMARY KEY (id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    CREATE TABLE todos (
      id bigint(20) NOT NULL AUTO_INCREMENT,
      description varchar(255) DEFAULT NULL,
      is_done bit(1) NOT NULL,
      target_date datetime(6) DEFAULT NULL,
      username varchar(255) DEFAULT NULL,
      title varchar(255) DEFAULT NULL,
      PRIMARY KEY (id)
    ) ENGINE=InnoDB AUTO_INCREMENT=8;
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
  clusterIP: None
